name: Build and Deploy Joomla Extension

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install zip -y

      - name: List Files in Current Directory (for debugging)
        run: ls -la

      - name: Create Zip File
        run: |
          mkdir -p dist
          zip -r dist/semantyca-extension.zip com_semantycanm

      - name: Prepare SSH Key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa     

      - name: Copy Extension to Server
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}  
        run: scp -o StrictHostKeyChecking=no -P $SERVER_PORT dist/semantyca-extension.zip $SERVER_USER@$SERVER_HOST:/tmp/

      - name: Install Extension
        env:
          SERVER_USER: ${{ secrets.SERVER_USER }}
          SERVER_HOST: ${{ secrets.SERVER_HOST }}
          SERVER_PORT: ${{ secrets.SERVER_PORT }}
          JOOMLA_PATH: ${{ secrets.JOOMLA_PATH }}
        run: |
          ssh -p $SERVER_PORT $SERVER_USER@$SERVER_HOST "php $JOOMLA_PATH/cli/joomla.php extension:install --path=/tmp/semantyca-extension.zip"   

     
